// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that answers questions about EggyPro protein powder, shipping, and company policies.
 *
 * - instantFAQAssistance - A function that provides instant answers to customer inquiries.
 * - InstantFAQAssistanceInput - The input type for the instantFAQAssistance function.
 * - InstantFAQAssistanceOutput - The return type for the instantFAQAssistance function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InstantFAQAssistanceInputSchema = z.object({
  question: z.string().describe('The question about EggyPro protein powder, shipping, or company policies.'),
});
export type InstantFAQAssistanceInput = z.infer<typeof InstantFAQAssistanceInputSchema>;

const InstantFAQAssistanceOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type InstantFAQAssistanceOutput = z.infer<typeof InstantFAQAssistanceOutputSchema>;

export async function instantFAQAssistance(input: InstantFAQAssistanceInput): Promise<InstantFAQAssistanceOutput> {
  return instantFAQAssistanceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'instantFAQAssistancePrompt',
  input: {schema: InstantFAQAssistanceInputSchema},
  output: {schema: InstantFAQAssistanceOutputSchema},
  prompt: `You are a customer support representative for EggyPro, an egg-based protein powder company.
  Answer the following question about EggyPro protein powder, shipping, or company policies.

  Question: {{{question}}}
  `,
});

const instantFAQAssistanceFlow = ai.defineFlow(
  {
    name: 'instantFAQAssistanceFlow',
    inputSchema: InstantFAQAssistanceInputSchema,
    outputSchema: InstantFAQAssistanceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
